# Application Properties
spring.application.name=connect
server.port=${PORT:8080}

# Database Configuration
spring.datasource.url=jdbc:postgresql://db.fitvucwbvyxouzmrafea.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=Nayepankh@2021
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Mail Server Configurations (Fallback/Mock enabled in service code if credentials are not set)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=manabatchey9@gmail.com
spring.mail.password=wibw bwml daty wpcl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# JWT Security Configurations
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000 
